### PR TITLE
docs: Add example for Apollo GraphQL + composition API

### PR DESCRIPTION
**Pull request by agualis**
Updates the existing `Graphql` example to make it compatible with `Vue 3` + `@vue/apollo-composable`.

The example needs a temporary patch until a pending [PR]( https://github.com/vuejs/vue-apollo/issues/1011) is merged in `vue-apollo` project. That's why we have to use specific   `"@vue/apollo-composable": "4.0.0-alpha.10"` version for now.

Implementation detail: 

I had to create a wrapper component `ComponentWithInjectedApollo` to globally provide _apollo client_  in the test. I would prefer not to do it and use some VTU option to call `global.provide` but I didn't find that option 🤷 Maybe you know how to do it.

Bonus: I could add an additional test to check what happens when the _Graphql request_ returns an error (It would involve adding some kind of error handling to the `VueApollo.vue` component).

### CODE REVIEW

**Comment by agualis** [comment]
Oops. Some tests are failing with `newMapConsumer.eachMapping is not a function`. First time I see this kind of error. I will wait to see if you have an explanation before starting investigating.

**Comment by afontcu** [comment]
Hi, thanks for this!! 🎉  this is great, it was one of the missing pieces to make sure VTL can support Vue 3, and I'm not experienced enough when it comes to vue apollo to make it work.

> I would prefer not to do it and use some VTU option to call global.provide but I didn't find that option

It does exist: https://vue-test-utils.vuejs.org/v2/api/#global-provide

**Comment by agualis** [comment]
> It does exist: https://vue-test-utils.vuejs.org/v2/api/#global-provide

I actually tried that but it didn't work. Maybe you can help to understand why...

**Comment by agualis** [comment]
>  it was one of the missing pieces to make sure VTL can support Vue 3

Happy if I can help with something else 😊

**Comment by afontcu** [comment]
> > It does exist: https://vue-test-utils.vuejs.org/v2/api/#global-provide
> 
> I actually tried that but it didn't work. Maybe you can help to understand why...

Sure! Can you share what failed? I'm also on the VTU team so I can run the issue internally if needed 👍

**Comment by agualis** [comment]
> Sure! Can you share what failed? I'm also on the VTU team so I can run the issue internally if needed 👍

If, instead of using `ComponentWithInjectedApollo`, you just render the `Component` like this: 

```javascript
  render(Component, {
      props: {id: '1'},
      global: {
        provide: {
          DefaultApolloClient: apolloClient,
        }
      }
  })
```

the apollo client won't be injected and you'll get this error when running the test: 

`Apollo Client with id default not found
`

**Comment by heywhy** [comment]
> > Sure! Can you share what failed? I'm also on the VTU team so I can run the issue internally if needed 👍
> 
> If, instead of using `ComponentWithInjectedApollo`, you just render the `Component` like this:
> 
> ```js
>   render(Component, {
>       props: {id: '1'},
>       global: {
>         provide: {
>           DefaultApolloClient: apolloClient,
>         }
>       }
>   })
> ```
> 
> the apollo client won't be injected and you'll get this error when running the test:
> 
> `Apollo Client with id default not found `

You should have something like this 👇 instead:

```ts
import { DefaultApolloClient } from '@vue/apollo-composable'

...

render(Component, {
  props: {id: '1'},
  global: {
    provide: {
      [DefaultApolloClient]: apolloClient,
    }
  }
})
```

**Comment by heywhy** [comment]
@agualis @afontcu You should refer to this [Vue 3 Project Template](https://github.com/heywhy/vite-graphql-setup) for proper testing infrastructure support using `@testing-library/vue`. And you can clone the repo to start your own project 😄 . Though, I will love your feedbacks.

**Comment by agualis** [comment]
> You should have something like this 👇 instead:

Oh. I missed that I needed square brackets because `DefaultApolloClient` is a `symbol`. Than you very much atanda! 

> Vue 3 Project Template 

I looks good. Thanks for sharing.

**Comment by afontcu** [comment]
Looks like we have some CI issues 🤔 I ran tests locally and got the following error:

imatge

**Comment by agualis** [comment]
Defined is not defined. To be or not to be 😅 

Which node version are you using? yarn or npm? 

woml

**Comment by agualis** [comment]
I recall that I had to use a fixed `apollo-composable`  version because I was having the same error (and we're not alone): 

https://github.com/vuejs/vue-apollo/issues/1085

I'll try to reproduce it in another machine. It's funny that we are also having a different error  in GHA CI 😅  (bug fragmentation 🤣 ).

**Comment by heywhy** [comment]
@agualis I will like you to invite me to the repository you are working on because I'm able to resolve the failing tests and I don't want to create a separate PR for this project or for your fork. see loom recording below:

https://www.loom.com/share/abf53aaedce448d89564afc22c1ebfcf

cc: @afontcu

**Comment by agualis** [comment]
> I will like you to invite me to the repository you are working on

I'm not sure if I'm following you @heywhy  I don't have another project, just the fork.

**Comment by heywhy** [comment]
> > I will like you to invite me to the repository you are working on
> 
> I'm not sure if I'm following you @heywhy I don't have another project, just the fork.

I don't want to create another fork of this project instead I want to push the changes directly to your own fork because I made the fixes on your fork but I don't have access to your fork so I can't push the changes

**Comment by afontcu** [comment]
Looks like this PR contains changes that are already there in `next`.  Can you make sure you check out from latest `next` changes? 🤗

**Comment by heywhy** [comment]
@afontcu I don't understand why the CI fails, can you help delete the cache for this PR workflow

Screen Shot 2020-12-16 at 1 38 51 PM

**Review by afontcu — APPROVED** [review]
Glad you got CI working! Looks mergeable, right?

**Comment by heywhy** [comment]
@agualis can you explain what went wrong??

**Comment by agualis** [comment]
Finally ready to merge 🎊 . It seems that `apollo+vue `ecosystem is very active right now and this affected our PR.  

@heywhy I enabled CI in my fork and I discovered that version 3.2.2 of `apollo client` was the one affecting our tests 😕  I didn't investigate the root cause but updating to the last stable one (3.3.6) fixed the problem. 

@afontcu  will keep an eye on this topic because apollo related dependencies will be fixed soon and we will be able to get rid of the nasty `postinstall patch`.

Thanks both for your patience and help 🙏

**Comment by afontcu** [comment]
Looks great :) Thank you for this!

**Pull request merged**
