### PR TITLE
feat: update Vue 2 version to use @testing-library/dom v8

### PR DESCRIPTION
**Pull request by oskarols**
Hi! 👋 I was told [here](https://github.com/testing-library/dom-testing-library/issues/1047#issuecomment-1218128916) that a contribution to bump `@testing-library/dom` to v8 would be happily received, so here I am 😄 
 
I realize I'm opening this against the wrong branch; there doesn't seem to be one for the Vue 2 version that continues from `v5.8.3`. Maybe you can assist me with what to do here? 

--- 

This updates the version of `@testing-library/dom` from v7 to v8 for Vue 2.x.

- Since the v8 version dropped support for Node 10, I cherry-picked this change as well.
- Using `^8.5.0` to be consistent with the Vue 3 version of the library.
- Tested this change on a large Nuxt 2 repo and everything worked as expected.

**Issues**
- There's an error when running `npm run validate`, unrelated to this change:
```
[typecheck] Error: Errors in typescript@4.9 for external dependencies:
[typecheck] ../node_modules/@types/inquirer/index.d.ts(80,76): error TS2344: Type 'T' does not satisfy the constraint 'Answers'.
[typecheck] ../node_modules/@types/inquirer/index.d.ts(84,91): error TS2344: Type 'TChoiceMap' does not satisfy the constraint 'Answers'.
[typecheck] ../node_modules/@types/inquirer/index.d.ts(84,105): error TS2344: Type 'T' does not satisfy the constraint 'Answers'.
[typecheck] ../node_modules/@types/inquirer/index.d.ts(139,43): error TS2344: Type 'T' does not satisfy the constraint 'Answers'.
[typecheck] ../node_modules/@types/inquirer/lib/objects/choices.d.ts(11,39): error TS2344: Type 'T' does not satisfy the constraint 'Answers'.
[typecheck] ../node_modules/@types/inquirer/lib/objects/choices.d.ts(11,61): error TS2344: Type 'T' does not satisfy the constraint 'Answers'.
[typecheck]
[typecheck]     at /vue-testing-library/node_modules/dtslint/bin/index.js:207:19
[typecheck]     at Generator.next (<anonymous>)
[typecheck]     at fulfilled (/vue-testing-library/node_modules/dtslint/bin/index.js:6:58)
[typecheck] npm run typecheck --silent exited with code 1
husky > pre-commit hook failed (add --no-verify to bypass)
```

### CODE REVIEW

**Comment by oskarols** [comment]
ping @afontcu ^ 😄

**Comment by saifahn** [comment]
@oskarols

I'm curious - why did you end up closing this PR?

@afontcu 

Is there any possibility of this being merged and released in a new v5 version of Vue Testing Library? Our team would like to use the `current` option in queries to help us build more accessible components with corresponding tests 🙂

**Comment by afontcu** [comment]
hi @saifahn! I don't have the bandwidth to work on that, but it should be possible by branching off latest v5 tag (https://github.com/testing-library/vue-testing-library/tree/v5.8.3) and submitting a PR there 👍

**Comment by oskarols** [comment]
@saifahn Understandably this didn't get any attention and we couldn't wait, so we used the `resolutions` field in Yarn to override the `@testing-library/dom` version.

**Comment by saifahn** [comment]
@afontcu 

Thanks for getting back to me!
I actually [created a fork](https://github.com/saifahn/vue-testing-library/tree/bump-vtl-5-to-testing-lib-8) branching off the v5.8.3 tag and made a commit. I was in the middle of making a PR when I noticed that I couldn't make a PR back to that tag - I can only compare the diff:

image

This makes sense because the tag simply points to a commit and is not something that can be updated. Perhaps we could make a separate branch that starts at the same point as v5.8.3 that could be used to track the v5 version and be used for releasing the v5 version?

If you agree with this approach, then we could reopen this PR and point it at that branch, seeing as the changes are the same as what I have done in my fork/branch as well. Looking forward to hearing your thoughts 🙂 

@oskarols 

Thanks for sharing your workaround. It looks like `overrides` may be what we may have to go with in npm if it comes to it.

**Comment by saifahn** [comment]
@afontcu 

Tagging you in case this slipped under the radar. As stated above, I didn't make a PR because even after forking the `v5.8.3` tag.

I wonder if you have any thoughts on my proposal? 😄

**Comment by afontcu** [comment]
hey!

> Perhaps we could make a separate branch that starts at the same point as v5.8.3 that could be used to track the v5 version and be used for releasing the v5 version?

Yeah, that sounds about right. I think it should be called `5.x`, so that semantic-release is able to pick it up as a follow-up branch for v5

**Comment by saifahn** [comment]
Great!

Do you think you could create the branch in this repository from the 5.8.3 tag? (Seeing as I don't have those permissions 😄)  

Then I can open a PR that will merge into that branch. (Or we could reopen this PR pointing there)

Thanks!

**Comment by afontcu** [comment]
hey @saifahn! this should be available in [v5.9](https://github.com/testing-library/vue-testing-library/releases/tag/v5.9.0.) !

**Comment by saifahn** [comment]
@afontcu Thanks so much for the update 💜

**Pull request closed without merging**
