### PR TITLE
allow vue-router creation through routes param from both jest and mocha (fix)

### PR DESCRIPTION
**Pull request by agualis**

### CODE REVIEW

**Comment by agualis** [comment]
Hey, this is embarrassing 😓 I tested the released version in my mocha project and it did not work cause there was a mistake in my code. I updated it again. Sorry for the inconvenience.

You will also notice that I deleted the mocha test as it was based in my wrong assumption that the require import would be undefined. With the new code, that won't  affect the coverage though.

**Comment by afontcu** [comment]
Hi! No worries 😃 Releasing a new patch version ASAP

**Comment by agualis** [comment]
That was blazing fast 🚀 I confirm that now Router works in mocha. You rock!

**Comment by afontcu** [comment]
you do! thanks for doing this 🙌

**Pull request merged**
