### PR TITLE
Semantic release

### LINKED ISSUE #81: Add semanting release bot
Other Testing Library members are using https://github.com/semantic-release/semantic-release to handle their releases.

It looks great not only because of the sensible version bumping, but also for all the automated tasks it handles (notifications, formalized commits,...).

Thoughts?

### PR DESCRIPTION
**Pull request by afontcu**
This PR closes #81.

This is just a draft PR to explore `semantic-release` and `commitizen`.

Tools:
https://github.com/semantic-release/semantic-release
https://github.com/commitizen/cz-cli

I've following semantic-release [getting started guide](https://semantic-release.gitbook.io/semantic-release/usage/getting-started), and also [the "official" config for Travis](https://github.com/semantic-release/semantic-release/blob/master/docs/03-recipes/travis.md). Also [this tutorial](https://medium.com/@schalkneethling/automate-package-releases-with-semantic-release-and-commitizen-d7d4c337f04f) came in handy.

I'm having a hard time getting a `--dry-run` execution to successfully perform all the required steps. I've used my account to provide tokens for both GitHub and npm, but got no luck when testing it out:

imatge

it might be due to running it _before_ having everything in place on `master`, but I was hoping I could test it out before merging anything.

### CODE REVIEW

**Comment by afontcu** [comment]
With the current implementation, `git commit` would trigger `commitizen`, so any contributor would be able to set the appropriate commit message.

**Comment by afontcu** [comment]
I'm wondering if we should use [kcd-scripts](https://github.com/kentcdodds/kcd-scripts) to avoid the hassle 🤔

**Comment by afontcu** [comment]
Build failed due to [commitizen only supporting node >= 10](https://github.com/commitizen/cz-cli/commit/8931c6b).

**Comment by dfcook** [comment]
> 
> imatge
> 

This looks like it's using https to make the push (asking for username and password) not your token.

> 
> I'm wondering if we should use kcd-scripts to avoid the hassle 🤔
> 

Are they easy enough to use? Anything that gives consistency with other testing libraries is a good think IMO.

**Comment by afontcu** [comment]
> This looks like it's using https to make the push (asking for username and password) not your token.

It is weird, though, because it created the appropriate GH token, and there's no cli option to push using SSH instead of https ([docs](https://semantic-release.gitbook.io/semantic-release/recipes/git-hosted-services/git-auth-ssh-keys)).

**Comment by afontcu** [comment]
> I'm wondering if we should use [kcd-scripts](https://github.com/kentcdodds/kcd-scripts) to avoid the hassle 🤔

Gave it a go in #86

**Comment by afontcu** [comment]
I like Kent's [idea](https://github.com/testing-library/vue-testing-library/pull/86#discussion_r314954893) to avoid `commitizen` and switch to a squash&merge strategy  instead (we could disable all merging strategies on the repo) so that we are responsible for writing [the right commit message](https://github.com/semantic-release/semantic-release/#commit-message-format).

**Comment by afontcu** [comment]
Closing in favor of #86

**Pull request closed without merging**
